---
title: "WOD-Predict"
author: "Mikey Ling"
date: "July 25, 2018"
output: html_document
---

## R Markdown

```{r}
library(xlsx)
library(stringi)
library(tibble)
library(stringr)
```

Read in the Excel File
```{r}
df <- read.xlsx("C:/Users/212475369/Desktop/WOD-Predict/PerformanceResultsMetcons.xlsx",1)
```

Find any description that contains "AMRAP"
1)
```{r}
workout_type <- "AMRAP"
df_amrap <- df[grepl(workout_type,df$Result.Type.Label),]
cat("Found ", dim(df_amrap)[1], " ", workout_type, " workouts out of ", dim(df)[1], " total workouts", end="\n", file="")
```

1A) which WOD Descriptions have "minute" in it
```{r}
df_1a <- df_amrap
df_1a <- as.data.frame(append(df_1a, list(time=NA), after=2))
df_1a <- as.data.frame(append(df_1a, list(minutes=0), after=2))
df_1a$time <-grepl('(?i)minute', df_1a$Component.Description)

```

1B) get minute value
```{r}
df_1b <- df_1a
df_1b$minutes[df_1b$time==TRUE] <- gsub(" ?(?i)minute.*$", "", df_1b$Component.Description[df_1a$time==TRUE])
```

1C) get Wall Ball count 
```{r}
df_1c <- df_1a
df_1c <- as.data.frame(append(df_1c, list(wb=0), after=2))
df_1c$wb <- grepl('(?i)wall',df_1c$Component.Description)
df_1c$wb[df_1c$wb==TRUE] <- gsub(" (?i)wall.*$", "\\1", df_1c$Component.Description[df_1c$wb==TRUE])
df_1c$wb[df_1c$wb!=FALSE] <- word(df_1c$wb[df_1c$wb!=FALSE], -1)
df_1c$minutes[df_1c$wb != FALSE] <-
# df_1c$wb[df_1c$wb!=FALSE] <- str_extract_all(df_1c$wb, "[0-9]+")
# df_1c <- as.data.frame(append(df_1c, list(wb_reps=NA), after=2))
# df_1c$wb_reps<- strsplit(toString(df_1c$Component.Description)," ")
# df_1c$wb_reps[df_1c$wb == TRUE] <- sapply(strsplit(as.character(df_1c$Component.Description[df_1c$wb==TRUE]), "\\."), function(x) x[[1]])
# hehe <-  strsplit(as.character(df_1c$wb[df_1c$wb!=FALSE]), " ")
# df_1c$wb_reps[df_1c$wb != FALSE] <- strsplit(as.character(df_1c$wb[df_1c$wb!=FALSE]), " ")
# unlist(df_1c$wb_reps)
# df_1c$wb_reps[!(is.na(df_1c$wb_reps))] <- df_1c$wb_reps[!(is.na(df_1c$wb_reps))]


# sapply(strsplit(as.character(df_1c$Component.Description), "\\."), function(x) x[[1]])
# df_1c$wb_reps[df_1c$wb!=FALSE] <- strsplit(gsub(" (?i)wall.*$", "\\1", df_1c$Component.Description[df_1c$wb!=FALSE])," ")
```

```{r}
test <- "20 minute 10 amrap of: my butt"
# results  <- gsub(" amrap.*$", "\\1", test)
results <- strsplit(gsub(" amrap.*$", "\\1", test), " ")
results[[1]][length(results[[1]])]
tail(results[[1]],n=1)
```

